#!/usr/bin/env python3
"""DK1 Lean Agent Memory bootstrap.

Idempotent: only creates files that don't exist; merges AGENTS.md carefully;
never clobbers existing PROJECT_STATE.md, SECURITY.md, DECISIONS.md content.

Usage:
    dk1-agent-memory-bootstrap.sh <repo_path> [project_display_name]

Behavior summary:
- mkdir -p <repo>/docs/agent-memory
- Create 6 docs/agent-memory/ files only if absent
- AGENTS.md: prepend handoff Mandatory-Read-Order / Change-Rules / After-Work
  ABOVE any existing `## graphify` section. Detect state by content length and
  marker strings — never clobber substantive content.
- dk1_agent.yaml: append `agent_memory:` block if absent; create minimal yaml
  if file missing
- HANDOFF_LOG.md: seed one initial entry
- GRAPHIFY_NOTES.md: auto-populate Last Run from graphify-out/GRAPH_REPORT.md

See ~/Projects/dk1-policy/standards/agent-memory.md for the policy.
"""
from __future__ import annotations

import json
import os
import sys
from datetime import date
from pathlib import Path


TODAY = date.today().isoformat()

# Locked decisions to pre-seed into every DECISIONS.md
LOCKED_DECISIONS = """\
### 2026-05-15 — Obsidian (`~/dk1-brain-vault/`) is canonical human knowledge

**Status:** Locked
**Area:** Operations / Knowledge
**Decision:** The Obsidian vault at `~/dk1-brain-vault/` is the human-facing
source of truth for DK1 strategy, business memory, meeting notes, and
operating principles. Agents must not auto-write to it.
**Reason:** Separation of human knowledge and agent state prevents drift and
preserves operator authorship.
**Implication for Agents:** Do not export agent-generated content into the
vault automatically. Reference vault content via `[[wikilinks]]` from
agent-memory files only.
**Reversal Rule:** Only reverse if Dan explicitly adopts a different vault
strategy.

---

### 2026-05-15 — Graphify is the agent orientation layer

**Status:** Locked
**Area:** Operations / Agent Workflow
**Decision:** Graphify (`graphify-out/GRAPH_REPORT.md`) is the structural map
agents read before broad codebase search. It is not a substitute for source
code.
**Reason:** Cuts token burn and grounds agent answers in the actual project
structure.
**Implication for Agents:** Read `graphify-out/GRAPH_REPORT.md` before running
multiple Grep/Glob calls. Use `graphify query/path/explain` for cross-module
questions.
**Reversal Rule:** Only reverse if a better orientation tool replaces Graphify.

---

### 2026-05-16 — Repo-level agent memory, no separate Mind vault

**Status:** Locked
**Area:** Operations / Agent Workflow
**Decision:** Use repo-level `docs/agent-memory/` markdown files for durable
agent memory. Do not stand up a separate Obsidian Mind vault, vector DB, or
memory service.
**Reason:** Lean, file-based, version-controlled, no new infrastructure.
**Implication for Agents:** Read AGENTS.md's Mandatory Read Order before
meaningful work; update HANDOFF_LOG.md after.
**Reversal Rule:** Only reverse if Dan adopts a different memory architecture.

---

### 2026-05-16 — CLAUDE.md is gitignored, auto-regenerated

**Status:** Locked
**Area:** Operations / Tooling
**Decision:** `CLAUDE.md` is gitignored across all DK1 repos because it is
auto-regenerated by claude-mem and other local tools.
**Reason:** Avoid noise in git history and merge conflicts on session
context.
**Implication for Agents:** Do not commit `CLAUDE.md`. Agent-durable rules
live in `AGENTS.md` (which IS committed).
**Reversal Rule:** Only reverse if CLAUDE.md content becomes stable enough to
track.
"""


def detect_project_state(repo: Path) -> Path | None:
    """Return path to existing PROJECT_STATE.md if any, else None."""
    candidates = [
        repo / "PROJECT_STATE.md",
        repo / "docs" / "PROJECT_STATE.md",
        repo / "docs" / "agent-memory" / "PROJECT_STATE.md",
    ]
    for p in candidates:
        if p.is_file():
            return p
    return None


def detect_security(repo: Path) -> Path | None:
    """Return path to existing SECURITY.md if any."""
    for p in (repo / "SECURITY.md", repo / "docs" / "SECURITY.md"):
        if p.is_file():
            return p
    return None


def existing_agents_state(p: Path) -> str:
    """Classify AGENTS.md state: 'absent', 'stub', 'substantive'."""
    if not p.is_file():
        return "absent"
    txt = p.read_text()
    if "Mandatory Read Order" in txt:
        return "already-merged"
    if len(txt.splitlines()) <= 15 and "## graphify" in txt:
        return "stub"
    return "substantive"


def graphify_metrics(repo: Path) -> dict:
    """Extract last-run mtime + node/edge/community counts from GRAPH_REPORT.md."""
    report = repo / "graphify-out" / "GRAPH_REPORT.md"
    out = {"present": False}
    if not report.is_file():
        return out
    out["present"] = True
    out["mtime"] = report.stat().st_mtime
    try:
        head = report.read_text()[:4000]
        # Look for pattern like "- 3490 nodes · 7610 edges · 185 communities"
        import re
        m = re.search(r"(\d+)\s*nodes.*?(\d+)\s*edges.*?(\d+)\s*communities", head)
        if m:
            out["nodes"] = int(m.group(1))
            out["edges"] = int(m.group(2))
            out["communities"] = int(m.group(3))
        # Look for "Built from commit: `<sha>`"
        cm = re.search(r"Built from commit:\s*`([0-9a-f]+)`", head)
        if cm:
            out["commit"] = cm.group(1)
    except Exception:
        pass
    return out


def agents_prepend_block(project_name: str, project_state_path: str) -> str:
    return f"""# AGENTS.md — {project_name}

This is a DK1 project. Agents must preserve product decisions, implementation
discipline, security posture, and operational clarity.

## Mandatory Read Order

Before making meaningful changes, read:

1. `{project_state_path}` — current state, open work, risks
2. `docs/agent-memory/DECISIONS.md` — locked decisions you must not reverse
3. `docs/agent-memory/RUNBOOK.md` — build, test, deploy, rollback
4. Latest entries in `docs/agent-memory/HANDOFF_LOG.md`
5. `docs/agent-memory/SECURITY_NOTES.md`
6. `docs/agent-memory/GRAPHIFY_NOTES.md` if Graphify has been run

For trivial work (typos, single-line fixes), the read order is advisory.
For anything touching architecture, schemas, auth, routes, or workflows,
read the full set.

## Change Rules

- Do not overwrite prior locked decisions unless Dan explicitly instructs it
- Do not introduce new architecture without documenting the decision in
  `DECISIONS.md`
- Do not add dependencies without a clear reason captured in `HANDOFF_LOG.md`
- Do not expose secrets, credentials, raw emails, raw client files, or
  private data
- Prefer small, reversible changes
- Preserve DK1 style: clean, controlled, professional, operationally useful

## After Meaningful Work

Update, in order of likelihood:

1. `docs/agent-memory/HANDOFF_LOG.md` — always (add a new dated entry)
2. `{project_state_path}` — if open work changed
3. `docs/agent-memory/DECISIONS.md` — if a decision was made or reversed
4. `docs/agent-memory/RUNBOOK.md` — if commands/tests/deploys/monitoring/rollback
   changed
5. `docs/agent-memory/SECURITY_NOTES.md` — if auth, permissions, secrets, or
   data exposure changed
6. `docs/agent-memory/GRAPHIFY_NOTES.md` — after rerunning Graphify

## Handoff Output Standard

Every `HANDOFF_LOG.md` entry must include: date, agent/tool, task summary,
files changed, commands run, results, decisions touched, security notes,
open issues, and recommended next action.

---
"""


def project_state_template(project_name: str) -> str:
    return f"""# PROJECT_STATE.md

## Project Snapshot

**Project Name:** {project_name}
**Owner:** DK1 / Dan Kim
**Current Stage:** _to be filled_
**Primary Goal:** _to be filled_
**Current Users / Audience:** _to be filled_
**Deployment Target:** _to be filled_
**Current Status:** Agent memory package initialized {TODAY}

## What This Project Is

_to be filled_

## What This Project Is Not

_to be filled — list boundaries_

## Current Product Direction

_to be filled_

## Current Technical Direction

_to be filled_

## Current UI / UX Direction

_to be filled_

## Current Open Work

| Priority | Work Item | Owner | Status | Notes |
|---|---|---|---|---|
| P0 | Fill project state from MEMORY index + recent commits | DK1 / agent | Open | Initial setup |

## Known Risks

| Risk | Severity | Mitigation |
|---|---|---|
| Stub content | Low | Hand-fill from MEMORY index next session |

## Last Updated

{TODAY} by dk1-agent-memory-bootstrap.sh
"""


def decisions_template() -> str:
    return f"""# DECISIONS.md

Locked decisions agents must not accidentally reverse.

## Status Values

`Proposed` · `Active` · `Locked` · `Deprecated` · `Reversed`

## Cross-Portfolio Locked Decisions

{LOCKED_DECISIONS}

## Project-Specific Decisions

_Add project-specific decisions below. Newest first._

### {TODAY} — Initialize repo-level agent memory

**Status:** Active
**Area:** Operations
**Decision:** Adopt the DK1 lean agent memory standard per
`~/Projects/dk1-policy/standards/agent-memory.md`.
**Reason:** Provides durable agent context without standing up new
infrastructure.
**Implication for Agents:** Read and update memory files per AGENTS.md.
**Reversal Rule:** Only reverse with explicit operator instruction.

---
"""


def runbook_template(has_makefile: bool, makefile_targets: list[str]) -> str:
    targets_table = ""
    if has_makefile and makefile_targets:
        rows = [f"| `make {t}` | _describe_ |" for t in makefile_targets[:15]]
        targets_table = (
            "\n## Makefile Targets\n\n"
            "| Command | Purpose |\n|---|---|\n"
            + "\n".join(rows)
            + "\n"
        )
    return f"""# RUNBOOK.md

## Local Development

```bash
# Fill: clone, install, env setup commands
```

## Environment Variables

List required variable names only; never values.

| Variable | Purpose | Required | Notes |
|---|---|---:|---|
| `ANTHROPIC_API_KEY` | LLM backend | Conditional | See dk1-ghtransna-orders/.env for canonical key |
{targets_table}
## Build

```bash
# Fill
```

## Test

```bash
# Fill
```

## Deploy

```bash
# Fill
```

## Monitoring

| Tool | Status | Notes |
|---|---|---|
| Sentry | _to be filled_ | |
| PostHog | _to be filled_ | |
| Logs | _to be filled_ | |

## Authentication / Authorization

_to be filled — provider, roles, row-level access model_

## Rollback

```bash
# Fill — how to revert a bad deploy
```

## Operational Checks (pre-prod)

- [ ] App starts cleanly
- [ ] Auth works
- [ ] Role/tenant access works
- [ ] Row-level access works where applicable
- [ ] Sentry receives errors
- [ ] PostHog receives expected events
- [ ] Logs scrubbed of secrets/PII
- [ ] Backup/restore path documented
- [ ] Deployment rollback documented

## Last Updated

{TODAY} by dk1-agent-memory-bootstrap.sh
"""


def handoff_log_initial(project_name: str) -> str:
    return f"""# HANDOFF_LOG.md

Durable memory trail. Add a new entry after every meaningful work session.
Newest first.

---

## {TODAY} — Initialize Agent Memory Package

**Agent / Tool:** dk1-agent-memory-bootstrap.sh
**Requested By:** DK1 / Dan
**Task:** Adopt DK1 Lean Agent Memory standard for {project_name}.

### Summary

Created the 6-file agent-memory package under `docs/agent-memory/`, merged
the Mandatory Read Order block into AGENTS.md above any existing `## graphify`
section, and (where applicable) added an `agent_memory:` block to
`dk1_agent.yaml`.

### Files Touched

| File | Change |
|---|---|
| `docs/agent-memory/PROJECT_STATE.md` | Created (if absent) |
| `docs/agent-memory/DECISIONS.md` | Created with locked cross-portfolio decisions |
| `docs/agent-memory/RUNBOOK.md` | Created (template) |
| `docs/agent-memory/HANDOFF_LOG.md` | Created (this entry) |
| `docs/agent-memory/GRAPHIFY_NOTES.md` | Created, auto-populated from current graphify-out |
| `docs/agent-memory/SECURITY_NOTES.md` | Created (thin pointer or full template) |
| `AGENTS.md` | Prepended Mandatory Read Order / Change Rules / After Work |
| `dk1_agent.yaml` | Created or appended `agent_memory:` block |

### Decisions

- Adopted the DK1 lean agent memory standard (cross-portfolio Locked)

### Security / Data Notes

No secrets or raw client data added. CLAUDE.md remains gitignored.

### Open Issues

| Priority | Issue | Recommended Next Action |
|---|---|---|
| P1 | PROJECT_STATE.md is template-only | Hand-fill from MEMORY index + recent commits |
| P1 | RUNBOOK.md sections are stubs | Fill build/test/deploy commands |

### Do Not Forget

- Read `docs/agent-memory/DECISIONS.md` before reversing any prior direction.
- Update this log after every meaningful session.

---
"""


def graphify_notes_template(metrics: dict) -> str:
    from datetime import datetime, timezone
    last_run_block = "**Last Run:** Not yet run\n"
    findings_block = "_None yet — run `graphify extract . --backend claude` then `graphify cluster-only .`_"
    if metrics.get("present"):
        ts = datetime.fromtimestamp(metrics["mtime"], tz=timezone.utc).isoformat()
        last_run_block = f"**Last Run:** {ts}\n"
        if "nodes" in metrics:
            last_run_block += f"**Scale:** {metrics['nodes']} nodes · {metrics['edges']} edges · {metrics['communities']} communities\n"
        if "commit" in metrics:
            last_run_block += f"**Built from commit:** `{metrics['commit']}`\n"
        findings_block = (
            "See `graphify-out/GRAPH_REPORT.md` for community hubs, god nodes, "
            "surprising connections, and knowledge gaps. Summarize the top 3–5 "
            "structural findings here after each meaningful rebuild."
        )
    return f"""# GRAPHIFY_NOTES.md

## Purpose

Agent-readable summary of how Graphify is used for this project.

## Status

{last_run_block}
**Output:** `graphify-out/` (gitignored — rebuild locally via `graphify update .`)

## Key Findings

{findings_block}

## How Agents Should Use This

1. Read `graphify-out/GRAPH_REPORT.md` before broad codebase search
2. Use `graphify query "<question>"`, `graphify path "<A>" "<B>"`,
   `graphify explain "<X>"` for cross-module questions instead of grep
3. After material structural changes, run `graphify update .` (AST-only,
   no API cost). After doc/PDF changes, run
   `graphify extract . --backend claude --max-concurrency 2` then
   `graphify cluster-only .`
4. Do not treat Graphify as a substitute for reading actual source files —
   it's the orientation layer, not the precision layer

## Hydration

Local launchd job `com.dk1.graphify-hydrate` runs daily at 4:00 AM ET.
Weekly staleness alert via `com.dk1.graphify-staleness` (Mon 7 AM →
`dk1-alerts-graphify` ntfy topic).

## Last Updated

{TODAY} by dk1-agent-memory-bootstrap.sh
"""


def security_notes_thin(repo_name: str) -> str:
    return f"""# SECURITY_NOTES.md

## Primary Spec

The canonical security spec for {repo_name} lives at `../SECURITY.md`
(repo root). This file is an agent-readable summary; the root file is the
source of truth.

## Agent-Specific Rules

- Never commit `.env*` files
- Never paste secrets, tokens, or API keys into prompts or memory files
- Never include `.env*` or `data/` in Graphify input — `.graphifyignore`
  enforces this; do not override
- Never auto-sync vault content (`~/dk1-brain-vault/`) into the repo without
  explicit operator review

## Data Classification (quick reference)

| Class | Examples | Agent Access |
|---|---|---|
| Internal | source code, repo docs | Allowed |
| Restricted | client data, raw emails, PII | Read-only via curated input mode |
| Secret | API keys, credentials | NEVER expose, log, or graph |

## Last Updated

{TODAY} by dk1-agent-memory-bootstrap.sh — see `../SECURITY.md` for spec.
"""


def security_notes_full(repo_name: str) -> str:
    return f"""# SECURITY_NOTES.md

This is the primary security spec for {repo_name}. (No `SECURITY.md` exists
at repo root; this file is canonical until one is created.)

## Security Posture

_to be filled — overall model_

## Authentication

- **Provider:** _to be filled_
- **Roles:** _to be filled_
- **Tenant model:** _to be filled_

## Authorization

_to be filled — role-based and row-level access_

## Data Classification

| Data Type | Sensitivity | Storage | Agent Access |
|---|---|---|---|
| Source code | Internal | Repo | Allowed |
| Product docs | Internal | Repo / Obsidian | Allowed |
| Client raw data | Restricted | MinIO / client storage | Curated-input mode only |
| Emails | Restricted | Email system | Never expose without approval |
| Credentials | Secret | Secret manager / env | Never ingest or print |

## Secrets Handling

- Do not commit secrets
- Do not paste secrets into prompts
- Do not include `.env*` in Graphify
- Do not print tokens or credentials in logs

## Monitoring

| Tool | Status | Notes |
|---|---|---|
| Sentry | _to be filled_ | |
| PostHog | _to be filled_ | |
| Logs | _to be filled_ | |

## Production Readiness Checklist

- [ ] Auth configured
- [ ] Authorization configured
- [ ] Tenant isolation tested
- [ ] Row-level security tested where applicable
- [ ] Logs scrubbed
- [ ] Error monitoring configured
- [ ] Analytics reviewed for data leakage
- [ ] Backup/restore path documented
- [ ] Rollback path documented

## Last Updated

{TODAY} by dk1-agent-memory-bootstrap.sh
"""


def minimal_agent_yaml(repo_name: str, project_name: str) -> str:
    return f"""agent_id: {repo_name}
project: {repo_name}
display_name: "{project_name}"
agent_type: service
data_classification: internal
description: "DK1 project. Filled by dk1-agent-memory-bootstrap.sh on {TODAY} — replace with real description."
node: macos
related_services: []

# Graphify graph metadata
graphify:
  enabled: true
  graph_path: graphify-out/GRAPH_REPORT.md
  freshness_sla_days: 7

# Agent memory package (DK1 lean agent memory standard)
agent_memory:
  enabled: true
  base_path: docs/agent-memory
  files:
    - PROJECT_STATE.md
    - DECISIONS.md
    - RUNBOOK.md
    - HANDOFF_LOG.md
    - GRAPHIFY_NOTES.md
    - SECURITY_NOTES.md
"""


def agent_memory_yaml_block() -> str:
    return f"""
# Agent memory package (DK1 lean agent memory standard, added {TODAY})
agent_memory:
  enabled: true
  base_path: docs/agent-memory
  files:
    - PROJECT_STATE.md
    - DECISIONS.md
    - RUNBOOK.md
    - HANDOFF_LOG.md
    - GRAPHIFY_NOTES.md
    - SECURITY_NOTES.md
"""


def get_makefile_targets(repo: Path) -> tuple[bool, list[str]]:
    mk = repo / "Makefile"
    if not mk.is_file():
        return False, []
    import re
    targets = []
    for line in mk.read_text().splitlines():
        m = re.match(r"^([a-zA-Z][a-zA-Z0-9_\-]+):\s*", line)
        if m:
            target = m.group(1)
            # Filter out generic non-target patterns
            if target not in ("PHONY", "all") or target not in targets:
                if target not in targets:
                    targets.append(target)
    return True, targets


def write_if_absent(path: Path, content: str) -> bool:
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def merge_agents_md(repo: Path, project_name: str, project_state_path: str) -> str:
    """Prepend handoff template to AGENTS.md, preserving any existing content."""
    agents = repo / "AGENTS.md"
    state = existing_agents_state(agents)
    prepend = agents_prepend_block(project_name, project_state_path)
    if state == "absent":
        agents.write_text(prepend + "\n## graphify\n\n(Run `graphify codex install` to populate.)\n")
        return "created"
    if state == "already-merged":
        return "skipped (already merged)"
    existing = agents.read_text().rstrip() + "\n"
    agents.write_text(prepend + "\n" + existing)
    return f"prepended ({state})"


def upsert_agent_yaml(repo: Path, repo_name: str, project_name: str) -> str:
    yaml_path = repo / "dk1_agent.yaml"
    if not yaml_path.exists():
        yaml_path.write_text(minimal_agent_yaml(repo_name, project_name))
        return "created minimal yaml"
    text = yaml_path.read_text()
    if "agent_memory:" in text:
        return "skipped (agent_memory: already present)"
    yaml_path.write_text(text.rstrip() + "\n" + agent_memory_yaml_block())
    return "appended agent_memory block"


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: dk1-agent-memory-bootstrap.sh <repo_path> [project_display_name]", file=sys.stderr)
        return 2
    repo = Path(sys.argv[1]).expanduser().resolve()
    if not repo.is_dir():
        print(f"Not a directory: {repo}", file=sys.stderr)
        return 1
    repo_name = repo.name
    project_name = sys.argv[2] if len(sys.argv) >= 3 else repo_name

    am_dir = repo / "docs" / "agent-memory"
    am_dir.mkdir(parents=True, exist_ok=True)

    actions = []

    # Detect existing PROJECT_STATE.md location
    existing_ps = detect_project_state(repo)
    if existing_ps and existing_ps.parent.name != "agent-memory":
        # Existing PROJECT_STATE.md at root or docs/ — point read order there
        try:
            ps_rel = existing_ps.relative_to(repo)
        except ValueError:
            ps_rel = existing_ps
        ps_path_for_agents = str(ps_rel)
        actions.append(f"PROJECT_STATE.md: kept existing at {ps_path_for_agents}")
    else:
        # Either no existing or already in docs/agent-memory/
        ps_target = am_dir / "PROJECT_STATE.md"
        if write_if_absent(ps_target, project_state_template(project_name)):
            actions.append(f"PROJECT_STATE.md: created at docs/agent-memory/PROJECT_STATE.md")
        else:
            actions.append(f"PROJECT_STATE.md: kept existing at docs/agent-memory/PROJECT_STATE.md")
        ps_path_for_agents = "docs/agent-memory/PROJECT_STATE.md"

    # DECISIONS.md
    decisions_path = am_dir / "DECISIONS.md"
    if write_if_absent(decisions_path, decisions_template()):
        actions.append("DECISIONS.md: created")
    else:
        actions.append("DECISIONS.md: kept existing")

    # RUNBOOK.md
    runbook_path = am_dir / "RUNBOOK.md"
    has_mk, targets = get_makefile_targets(repo)
    if write_if_absent(runbook_path, runbook_template(has_mk, targets)):
        actions.append(f"RUNBOOK.md: created ({len(targets)} Makefile targets enumerated)" if has_mk else "RUNBOOK.md: created")
    else:
        actions.append("RUNBOOK.md: kept existing")

    # HANDOFF_LOG.md
    handoff_path = am_dir / "HANDOFF_LOG.md"
    if write_if_absent(handoff_path, handoff_log_initial(project_name)):
        actions.append("HANDOFF_LOG.md: created with initial entry")
    else:
        actions.append("HANDOFF_LOG.md: kept existing")

    # GRAPHIFY_NOTES.md
    metrics = graphify_metrics(repo)
    notes_path = am_dir / "GRAPHIFY_NOTES.md"
    if write_if_absent(notes_path, graphify_notes_template(metrics)):
        if metrics.get("present"):
            actions.append(f"GRAPHIFY_NOTES.md: created (auto-populated {metrics.get('nodes', '?')} nodes)")
        else:
            actions.append("GRAPHIFY_NOTES.md: created (no graphify-out found)")
    else:
        actions.append("GRAPHIFY_NOTES.md: kept existing")

    # SECURITY_NOTES.md (thin vs full based on existing SECURITY.md)
    sec_existing = detect_security(repo)
    sec_notes_path = am_dir / "SECURITY_NOTES.md"
    if sec_existing:
        if write_if_absent(sec_notes_path, security_notes_thin(project_name)):
            actions.append(f"SECURITY_NOTES.md: created (thin; cross-refs {sec_existing.relative_to(repo)})")
        else:
            actions.append("SECURITY_NOTES.md: kept existing")
    else:
        if write_if_absent(sec_notes_path, security_notes_full(project_name)):
            actions.append("SECURITY_NOTES.md: created (full template, no root SECURITY.md)")
        else:
            actions.append("SECURITY_NOTES.md: kept existing")

    # AGENTS.md merge
    agents_result = merge_agents_md(repo, project_name, ps_path_for_agents)
    actions.append(f"AGENTS.md: {agents_result}")

    # dk1_agent.yaml upsert
    yaml_result = upsert_agent_yaml(repo, repo_name, project_name)
    actions.append(f"dk1_agent.yaml: {yaml_result}")

    # Report
    print(f"DK1 agent memory bootstrap — {project_name}")
    print(f"  repo: {repo}")
    print(f"  agent-memory dir: {am_dir}")
    for a in actions:
        print(f"  • {a}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
